/*
 * Glossaire : chaque terme technique affiché sur la fiche a son explication ici.
 * Dans le code, on écrit terme("sri", "SRI") pour afficher le mot avec son infobulle.
 */
const GLOSSAIRE = {
  lei: "Identifiant international (norme ISO 17442) de l'entité juridique, ici le fonds. Il permet de le retrouver sans ambiguïté dans les registres officiels.",
  cotation_ue: "Bourses et plateformes de négociation de l'Union européenne où cette part peut s'acheter, d'après le registre FIRDS tenu par l'ESMA, le régulateur européen des marchés. Un marché réglementé est une bourse principale ; les autres plateformes sont des systèmes de négociation secondaires.",
  isin: "Code unique de 12 caractères qui identifie un fonds (ou une part de fonds) dans le monde entier. Les 2 premières lettres indiquent le pays d'enregistrement.",
  ticker: "Code court utilisé en Bourse pour acheter un ETF (ex. CW8). Un même ETF peut avoir plusieurs tickers selon la place de cotation.",
  societe_gestion: "L'entreprise qui gère le fonds : elle choisit les placements et prélève les frais de gestion.",
  domicile: "Pays où le fonds est juridiquement enregistré. Il influence la fiscalité et l'éligibilité au PEA.",
  opcvm: "Organisme de placement collectif : l'argent de nombreux épargnants est mis en commun et investi par un gérant. Les SICAV et les FCP sont des OPCVM.",
  etf: "Fonds coté en Bourse, qui s'achète comme une action. Il cherche en général à reproduire un indice, à faible coût.",
  indiciel: "Fonds qui cherche à copier un indice (ex. le CAC 40) au lieu d'essayer de le battre. Frais généralement bas.",
  actif: "Fonds dont le gérant choisit lui-même les placements pour essayer de faire mieux que le marché. Frais généralement plus élevés.",
  nourricier: "Fonds qui investit la quasi-totalité de son argent dans un autre fonds (le « maître »). Il ajoute souvent ses propres frais par-dessus.",
  fonds_de_fonds: "Fonds qui investit dans d'autres fonds plutôt que directement dans des actions ou des obligations. Vous payez donc deux niveaux de frais.",
  formule: "Fonds dont le résultat final dépend d'une règle de calcul fixée à l'avance (ex. « 70 % de la hausse du CAC 40 »), souvent avec une protection partielle du capital à une date précise.",
  indice: "Panier de titres qui sert de référence pour mesurer un marché (ex. CAC 40, S&P 500, MSCI World).",
  encours: "Montant total d'argent géré par le fonds. Un très petit fonds (moins de 50 M€ environ) risque davantage d'être fermé ou fusionné.",
  sri: "Indicateur synthétique de risque, obligatoire dans le DIC. De 1 (risque très faible) à 7 (risque très élevé). Il combine la volatilité et le risque de crédit.",
  dic: "Document d'informations clés (KID en anglais) : 3 pages obligatoires qui résument le fonds, ses risques et ses frais.",
  volatilite: "Mesure de l'ampleur des variations de prix sur un an. Une volatilité de 15 % signifie qu'une variation annuelle de ±15 % est assez courante.",
  max_drawdown: "Plus forte baisse enregistrée entre un point haut et le point bas suivant. C'est la pire perte qu'aurait subie un investisseur arrivé au mauvais moment.",
  risque_change: "Risque de perdre de l'argent parce qu'une devise étrangère (ex. le dollar) baisse face à l'euro, même si les placements eux-mêmes montent.",
  risque_liquidite: "Risque de ne pas pouvoir récupérer son argent rapidement, ou seulement avec une décote.",
  risque_credit: "Risque que l'emprunteur (entreprise ou État) ne rembourse pas sa dette. Concerne surtout les fonds obligataires.",
  haut_rendement: "Obligations d'entreprises jugées plus fragiles (notation inférieure à BBB-). Elles rapportent plus car le risque de défaut est plus élevé.",
  notation: "Note donnée par une agence (S&P, Moody's, Fitch) sur la capacité d'un emprunteur à rembourser : de AAA (très sûr) à D (défaut).",
  sensibilite: "De combien le fonds baisse en % si les taux d'intérêt montent de 1 point. Une sensibilité de 4 donne environ −4 %.",
  frais_courants: "Frais prélevés chaque année directement sur la valeur du fonds (gestion, administration…). Vous ne les voyez pas passer, mais ils réduisent la performance.",
  frais_entree: "Pourcentage prélevé sur chaque somme investie. Souvent négociable, voire nul en ligne ou en assurance-vie.",
  frais_sortie: "Pourcentage prélevé quand vous revendez vos parts.",
  surperformance: "Commission supplémentaire versée au gérant quand il bat son objectif. Elle peut coûter cher les bonnes années.",
  frais_transaction: "Coût des achats et ventes de titres réalisés par le gérant. Ils s'ajoutent aux frais courants.",
  tracking_difference: "Écart de performance annuel entre le fonds indiciel et son indice. Négatif = le fonds fait moins bien que l'indice (surtout à cause des frais).",
  replication_physique: "Le fonds achète réellement les titres de l'indice.",
  replication_synthetique: "Le fonds détient un autre panier de titres et échange sa performance contre celle de l'indice via un contrat (swap) avec une banque.",
  swap: "Contrat entre le fonds et une banque qui échangent les performances de deux paniers. Si la banque fait défaut, une partie du gain peut être perdue.",
  contrepartie: "La banque qui s'est engagée à verser la performance de l'indice. Le risque de contrepartie, c'est le risque qu'elle ne tienne pas cet engagement.",
  derives: "Contrats financiers (options, contrats à terme, swaps…) dont la valeur dépend d'un autre actif. Ils servent à se protéger ou à amplifier une exposition.",
  levier: "Mécanisme qui amplifie les gains ET les pertes (ex. un levier ×2 double les variations de l'indice).",
  capitalisation: "Part capitalisante : les revenus (dividendes, coupons) sont réinvestis automatiquement dans le fonds.",
  distribution: "Part distribuante : les revenus sont versés régulièrement aux porteurs (et donc imposables chaque année hors enveloppe).",
  couverture_change: "Part « hedged » : le fonds neutralise l'effet des variations des devises face à l'euro. Cela a un coût, mais supprime le risque de change.",
  pea: "Plan d'épargne en actions : enveloppe fiscale française, réservée aux fonds investis au moins à 75 % en actions européennes (ou via réplication synthétique).",
  assurance_vie: "Enveloppe fiscale française. Le fonds doit être référencé par l'assureur de votre contrat.",
  liquidite: "Fréquence à laquelle vous pouvez acheter ou revendre vos parts (tous les jours, toutes les semaines…).",
  preavis: "Délai à respecter avant que votre ordre de vente soit exécuté.",
  classe_actifs: "Grande famille de placements : actions, obligations, monétaire (placements très courts et peu risqués), immobilier, matières premières.",
  top10: "Les 10 plus grosses positions du fonds. Plus leur poids total est élevé, plus le fonds dépend de quelques titres.",
  duree_recommandee: "Durée minimale de placement conseillée par la société de gestion dans le DIC.",
  part: "Un même fonds peut exister en plusieurs « parts » (ou classes) : même portefeuille, mais frais, devise, montant minimum ou traitement des revenus différents. Chaque part a son propre ISIN.",
  classification_amf: "Catégorie officielle attribuée par l'AMF aux fonds français. Elle impose des règles d'investissement minimales (ex. « Actions françaises » = au moins 60 % en actions françaises).",
  valeur_liquidative: "Prix d'une part du fonds, calculé par la société de gestion (en général chaque jour). C'est à ce prix que l'on achète ou revend ses parts.",
  analyse_style: "Méthode maison : on cherche quel mélange de placements de référence (actions US, zone euro, Japon, émergents, obligations, monétaire…) reproduit le mieux les variations passées du fonds. Cela révèle son exposition réelle, même quand il passe par des dérivés ou d'autres fonds.",
  r2: "Qualité de la reproduction, de 0 à 100 %. À plus de 90 %, les variations du fonds sont presque entièrement expliquées par le mélange trouvé : l'estimation est fiable.",
  inventaire: "Liste complète des placements détenus par le fonds à la date du rapport (nom, devise, montant, part de l'actif). Elle est publiée dans le rapport annuel ou semestriel, et nous la lisons ligne par ligne.",
  panier_substitution: "Titres réellement détenus par un fonds à réplication synthétique. Ils servent de garantie ; la performance de l'indice est obtenue via un swap.",
  monte_carlo: "Méthode qui simule des milliers d'avenirs possibles, en tirant au hasard des périodes du passé (bonnes et mauvaises), au lieu d'en imaginer un seul. On regarde ensuite comment les résultats se répartissent : c'est une façon honnête de montrer l'incertitude.",
  diversification: "Répartir son argent entre des placements qui ne montent et ne baissent pas tous en même temps. Le risque de l'ensemble devient plus faible que la moyenne des risques de chaque placement.",
  correlation: "Mesure, de -1 à 1, à quel point deux placements évoluent ensemble. Proche de 1 : ils montent et baissent en même temps. Proche de 0 ou négatif : ils se compensent en partie.",
  inflation: "Hausse générale des prix. Avec 2 % d'inflation par an, 100 € d'aujourd'hui n'achètent plus que l'équivalent d'environ 82 € dans 10 ans.",
  performance_annualisee: "Gain (ou perte) moyen par an sur la période. Ex. +5 % annualisé sur 3 ans ≈ +15,8 % au total."
};
